# Numpy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr = np.array(mylist)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

By default, numpy often returns floating point numbers in order to preserve some sort of precision

In [16]:
# 2-D array
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
# Rerturns evenly spaced numbers over a specified interval
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
# Creates an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random distributions of data

In [24]:
np.random.rand(1)

array([0.9856006])

In [26]:
np.random.rand(5,2)

array([[0.81384115, 0.89086847],
       [0.86174772, 0.37050669],
       [0.32023748, 0.37555393],
       [0.41769864, 0.42870294],
       [0.72800056, 0.18275356]])

In [28]:
np.random.randn(10)

array([ 0.62026062,  0.96280139, -0.23824028, -0.38396057,  1.91960165,
       -0.34458812, -0.72769629,  0.17387201,  0.21082   , -1.14757536])

In [30]:
np.random.rand(2)

array([0.91267988, 0.59770656])

In [31]:
np.random.rand(2,3)

array([[0.89015101, 0.32704363, 0.15372354],
       [0.92477131, 0.33740314, 0.3884585 ]])

In [32]:
type(np.random.rand(2,3))

numpy.ndarray

In [33]:
np.random.randint(0, 101)

83

In [34]:
np.random.randint(0, 101, 5)

array([ 3, 57, 99, 28, 42])

In [37]:
np.random.randint(0, 101, (4,5))

array([[82, 86, 74, 74, 87],
       [99, 23,  2, 21, 52],
       [ 1, 87, 29, 37,  1],
       [63, 59, 20, 32, 75]])

## np.random.seed

setting seed number will be really important for being able to repeat random distributions in order to test different models on them or test different visualization methods

In [38]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

attributes or methods you can call off an existing numpy array

In [39]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr = np.random.randint(0, 101, 10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [42]:
ranarr.max()

99

In [43]:
ranarr.min()

2

In [44]:
# Find index location of the max number
ranarr.argmax()

5

In [45]:
ranarr.argmin()

7

In [46]:
ranarr.dtype

dtype('int64')

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr.shape

(25,)

In [49]:
arr = arr.reshape(5, 5)

In [50]:
arr.shape

(5, 5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])